STANDARD_BUTTON_WIDTH = 15
STANDARD_BUTTON_HEIGHT = 7
STANDARD_PADX = 10
STANDARD_PADY = 10

STANDARD_FAMILY_FONT = "Tahoma"
STANDARD_SIZE_TEXT = 15

POPUP_BUTTON_WIDTH = 10
POPUP_BUTTON_HEIGHT = 5
POPUP_PADX = 5
POPUP_PADY = 5

POPUP_FAMILY_FONT = "Tahoma"
POPUP_SIZE_TEXT = 10

CANVAS_HEIGHT = 800
CANVAS_WIDTH = 1200

TOP_SIZE = 20
TOP_COLOR = "BLUE"
TOP_COLOR_CHOICE = "ORANGE"
TOP_COLOR_PAINT = "RED"
TOP_OUTLINE = "BLACK"
TOP_WIDTH = 5
LINE_WIDTH = 5
LINE_COLOR = "GRAY"

COLOR_DELETE = "WHITE"

GAME_REGIME = ("Демонстрация", "Тренажер", "Задачи")
DEMONSTRATE_REGIME = ("По шагово", "Анимировано", "Мгновенно")

ANIMATE_PAUSE = 2


class Status:
    Nothing = 0
    AddTop = 1
    ConnectTops = 2
    DeleteTops = 3
